# Generated by Django 2.2.3 on 2019-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='static/main/images/article_generic.png', upload_to=''),
        ),
    ]
