# Generated by Django 2.2.3 on 2019-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190727_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='UpdatedAt',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
