# Generated by Django 2.2.3 on 2019-08-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190801_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='designation',
        ),
    ]
