# Generated by Django 2.2.3 on 2019-08-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190805_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='author',
            name='reason',
        ),
    ]
